"""add new column

Revision ID: 02aa7c67ea77
Revises: 0c4bd5ded11e
Create Date: 2023-10-03 19:23:54.864619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02aa7c67ea77'
down_revision: Union[str, None] = '0c4bd5ded11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'user_id')
    # ### end Alembic commands ###
