"""add new column

Revision ID: 43c26586c88e
Revises: 
Create Date: 2023-10-03 16:01:59.778008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c26586c88e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('status', sa.Enum('wanted', 'available', 'readed', name='bookstatus'), nullable=True))
    op.drop_column('library', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('library', 'status')
    # ### end Alembic commands ###
