"""New changes

Revision ID: 55dc6b8c6f35
Revises: 02aa7c67ea77
Create Date: 2023-10-10 15:25:19.906459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dc6b8c6f35'
down_revision: Union[str, None] = '02aa7c67ea77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_library_id', table_name='library')
    op.create_index(op.f('ix_library_id'), 'library', ['id'], unique=True)
    op.drop_column('library', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_library_id'), table_name='library')
    op.create_index('ix_library_id', 'library', ['id'], unique=False)
    # ### end Alembic commands ###
