"""forum migration

Revision ID: 83b60ae04000
Revises: 99226ba6bedf
Create Date: 2023-10-13 21:50:57.236114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b60ae04000'
down_revision: Union[str, None] = '99226ba6bedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_library_id', table_name='library')
    op.drop_table('library')
    op.drop_index('ix_TopicMessages_id', table_name='TopicMessages')
    op.drop_table('TopicMessages')
    op.drop_index('ix_topic_id', table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topic_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='topic_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_topic_id', 'topic', ['id'], unique=False)
    op.create_table('TopicMessages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TopicMessages_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='TopicMessages_topic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='TopicMessages_pkey')
    )
    op.create_index('ix_TopicMessages_id', 'TopicMessages', ['id'], unique=False)
    op.create_table('library',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('wanted', 'available', 'readed', name='bookstatus'), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genres', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('series', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='library_pkey')
    )
    op.create_index('ix_library_id', 'library', ['id'], unique=False)
    # ### end Alembic commands ###
